# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Piing user' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Piing user
	
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire', '~> 4.5'
  
end

